petfriends_almoxarifado:
  name: petfriends-almoxarifado
  replicas: 1
  image: petfriends/petfriends-almoxarifado
  tag: "latest"
  imagePullPolicy: IfNotPresent
  service:
    type: ClusterIP
    port: 8081
    targetPort: 8081
  cm:
    DATABASE_NAME: "almoxarifado"

almoxarifado_db:
  name: almoxarifado-db
  replicas: 1
  image: mongo
  tag: "8.2.2-noble"
  imagePullPolicy: IfNotPresent
  service:
    type: ClusterIP
    port: 27017
    targetPort: 27017

petfriends_pedido:
  name: petfriends-pedido
  replicas: 1
  image: petfriends/petfriends-pedido
  tag: "latest"
  imagePullPolicy: IfNotPresent
  service:
    type: ClusterIP
    port: 8082
    targetPort: 8082
  cm:
    DATABASE_NAME: "pedido"

pedido_db:
  name: pedido-db
  replicas: 1
  image: mongo
  tag: "8.2.2-noble"
  imagePullPolicy: IfNotPresent
  service:
    type: ClusterIP
    port: 27017
    targetPort: 27017

petfriends_transporte:
  name: petfriends-transporte
  replicas: 1
  image: petfriends/petfriends-transporte
  tag: "latest"
  imagePullPolicy: IfNotPresent
  service:
    type: ClusterIP
    port: 8083
    targetPort: 8083
  cm:
    DATABASE_NAME: "transporte"

transporte_db:
  name: transporte-db
  replicas: 1
  image: mongo
  tag: "8.2.2-noble"
  imagePullPolicy: IfNotPresent
  service:
    type: ClusterIP
    port: 27017
    targetPort: 27017

petfriends_gateway:
  name: petfriends-gateway
  replicas: 1
  image: petfriends/petfriends-gateway
  tag: "latest"
  imagePullPolicy: IfNotPresent
  service:
    type: NodePort
    port: 8080
    targetPort: 8080
    nodePort: 30070

consul:
  name: consul
  replicas: 1
  image: hashicorp/consul
  tag: "latest"
  imagePullPolicy: IfNotPresent
  command:
    - "consul"
    - "agent"
    - "-dev"
    - "-client=0.0.0.0"
    - "-ui"
  service:
    type: NodePort
    http:
      port: 8500
      targetPort: 8500
      nodePort: 30080
    dns:
      port: 8600
      targetPort: 8600

kafka:
  name: kafka
  replicas: 1
  image: confluentinc/cp-kafka
  tag: "8.1.0"
  imagePullPolicy: IfNotPresent
  service:
    broker:
      type: ClusterIP
      port: 9092
      targetPort: 9092
    controller:
      port: 9093
      targetPort: 9093
  cm:
    KAFKA_PROCESS_ROLES: "broker,controller"
    KAFKA_NODE_ID: "1"
    KAFKA_CONTROLLER_LISTENERS: "CONTROLLER://0.0.0.0:9093"
    KAFKA_CONTROLLER_LISTENER_NAMES: "CONTROLLER"
    KAFKA_LISTENERS: "PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093"
    KAFKA_ADVERTISED_LISTENERS: "PLAINTEXT://kafka-hs:9092"
    KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "PLAINTEXT:PLAINTEXT,CONTROLLER:PLAINTEXT"
    KAFKA_INTER_BROKER_LISTENER_NAME: "PLAINTEXT"
    KAFKA_CONTROLLER_QUORUM_VOTERS: "1@kafka-hs:9093"
    KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: "1"
