server:
  port: 8081

spring:
  application:
    name: petfriends-almoxarifado

  data:
    mongodb:
      uri: ${MONGODB_URI}
      database: ${MONGODB_DATABASE}
      auto-index-creation: true

  cloud:
    function:
      definition: pedidoCriado;pedidoCancelado;pedidoSeparado

    stream:
      kafka:
        binder:
          brokers: ${KAFKA_BOOTSTRAP_SERVERS}
          enableObservation: false

      bindings:
        pedido-reserva-concluido-out-0:
          destination: pedido-reserva-concluido-events
          content-type: application/json

        pedido-reserva-falhou-out-0:
          destination: pedido-reserva-falhou-events
          content-type: application/json

        pedidoCriado-in-0:
          destination: pedido-criado-events
          group: petfriends-almoxarifado

        pedidoCancelado-in-0:
          destination: pedido-cancelado-events
          group: petfriends-almoxarifado

        pedidoSeparado-in-0:
          destination: pedido-separado-events
          group: petfriends-almoxarifado

axon:
  serializer:
    general: jackson
    events: jackson
    messages: jackson

  axonserver:
    enabled: false

management:
  endpoints:
    web:
      exposure:
        include: health